const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){document.body.classList.add('motion');const reveals=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveals.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>reveals.observe(e));}
const hero=document.querySelector('.hero-image'),progress=document.querySelector('.progress');let ticking=false;function onScroll(){if(!ticking){requestAnimationFrame(()=>{const y=window.scrollY,range=document.documentElement.scrollHeight-innerHeight;progress.style.width=(range>0?y/range*100:0)+'%';if(!reduced&&y<innerHeight*1.2)hero.style.transform=`translateY(${y*.19}px) scale(1.06)`;ticking=false});ticking=true}}addEventListener('scroll',onScroll,{passive:true});onScroll();
if(!reduced){const dust=document.querySelector('.dust');for(let i=0;i<16;i++){const el=document.createElement('i');el.style.left=(5+Math.random()*90)+'%';el.style.top=(20+Math.random()*70)+'%';el.style.animationDelay=(-Math.random()*10)+'s';el.style.animationDuration=(7+Math.random()*7)+'s';dust.append(el)}}
const chapters=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)document.querySelector('#chapter-number').textContent=e.target.dataset.chapter}),{rootMargin:'-25% 0px -35% 0px'});document.querySelectorAll('.chapter').forEach(e=>chapters.observe(e));
const date=new Date('2027-02-14T16:30:00+05:30').getTime();function updateCount(){const distance=Math.max(0,date-Date.now()),s=Math.floor(distance/1000);const values={days:Math.floor(s/86400),hours:Math.floor(s/3600)%24,minutes:Math.floor(s/60)%60,seconds:s%60};Object.entries(values).forEach(([k,v])=>document.getElementById(k).textContent=String(v).padStart(2,'0'));if(!distance)document.querySelector('.countdown').setAttribute('aria-label','The wedding day has arrived')}updateCount();setInterval(updateCount,1000);
const rsvp=document.querySelector('#rsvp-dialog');document.querySelectorAll('[data-rsvp]').forEach(b=>b.addEventListener('click',()=>rsvp.showModal()));document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
const form=document.querySelector('#rsvp-form'),result=document.querySelector('#rsvp-result');form.elements.attendance.addEventListener('change',()=>{form.elements.guests.disabled=form.elements.attendance.value!=='Joyfully attending'});form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')).trim();if(!name){form.elements.name.setCustomValidity('Please enter your name.');form.elements.name.reportValidity();return}form.elements.name.setCustomValidity('');const attending=data.get('attendance')==='Joyfully attending';const message=`Dear Aarya & Arjun,\n\n${name}: ${data.get('attendance')}.${attending?'\nGuests (including me): '+data.get('guests'):''}\nWedding: 14 February 2027${String(data.get('note')).trim()?'\n\n'+String(data.get('note')).trim():''}\n\nWith love,\n${name}`;document.querySelector('#reply-text').textContent=message;document.querySelector('#whatsapp').href='https://wa.me/?text='+encodeURIComponent(message);form.hidden=true;result.hidden=false});form.elements.name.addEventListener('input',()=>form.elements.name.setCustomValidity(''));document.querySelector('#edit-reply').addEventListener('click',()=>{form.hidden=false;result.hidden=true});
const photo=document.querySelector('#photo-dialog');document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{const img=document.querySelector('#full-photo');img.src=b.dataset.image;img.alt=b.querySelector('img').alt;document.querySelector('#full-caption').textContent=b.dataset.caption;photo.showModal()}));
function toast(text){const t=document.querySelector('.toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4000)}
document.querySelector('#calendar').addEventListener('click',()=>{const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Royal Garden//Wedding Invitation//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:aarya-arjun-20270214@royalgarden.example','DTSTAMP:20260919T000000Z','DTSTART:20270214T110000Z','DTEND:20270214T170000Z','SUMMARY:Aarya & Arjun Wedding (Demo)','LOCATION:The Rose Palace - fictional venue - Udaipur India','DESCRIPTION:Wedding ceremony at 4:30 PM IST. Reception at 7:30 PM IST. Fictional invitation demo.','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aarya-arjun-wedding.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Your calendar invitation is ready to open.')});
