const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reduced){document.body.classList.add('motion');const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el))}
const opening=document.querySelector('.opening'),hero=document.querySelector('.hero-image'),heroCopy=document.querySelector('.hero-copy'),film=document.querySelector('.film'),frames=[...document.querySelectorAll('.film-image')],captions=[...document.querySelectorAll('.film-caption')],tracks=[...document.querySelectorAll('.chapter-track>span')];let queued=false,last=-1;const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
function paint(){queued=false;const range=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=(range>0?scrollY/range*100:0)+'%';if(reduced)return;const o=opening.getBoundingClientRect(),hp=clamp(-o.top/(opening.offsetHeight-innerHeight),0,1);hero.style.transform=`scale(${1+hp*.2}) translateY(${hp*2}%)`;heroCopy.style.opacity=1-hp*.85;heroCopy.style.translate=`0 ${-hp*75}px`;const r=film.getBoundingClientRect(),fp=clamp(-r.top/(film.offsetHeight-innerHeight),0,.9999),idx=Math.floor(fp*3),local=fp*3-idx;if(idx!==last){last=idx;frames.forEach((el,i)=>el.classList.toggle('active',i===idx));captions.forEach((el,i)=>el.classList.toggle('active',i===idx));tracks.forEach((el,i)=>el.classList.toggle('active',i===idx));document.querySelector('#chapter-number').textContent=`0${idx+1} / 03`}frames[idx].style.transform=`scale(${1.03+local*.12}) translateX(${(local-.5)*-2}%)`;}
function requestPaint(){if(!queued){queued=true;requestAnimationFrame(paint)}}addEventListener('scroll',requestPaint,{passive:true});addEventListener('resize',requestPaint);paint();
if(!reduced){const dust=document.querySelector('.particles');for(let i=0;i<22;i++){const e=document.createElement('i');e.style.left=(Math.random()*100)+'%';e.style.top=(30+Math.random()*65)+'%';e.style.animationDelay=(-Math.random()*10)+'s';e.style.animationDuration=(7+Math.random()*6)+'s';dust.append(e)}}
const date=new Date('2027-02-14T10:30:00+05:30').getTime();function updateCount(){const distance=Math.max(0,date-Date.now()),s=Math.floor(distance/1000);const values={days:Math.floor(s/86400),hours:Math.floor(s/3600)%24,minutes:Math.floor(s/60)%60,seconds:s%60};Object.entries(values).forEach(([k,v])=>document.getElementById(k).textContent=String(v).padStart(2,'0'));if(!distance)document.querySelector('.countdown').setAttribute('aria-label','The wedding day has arrived')}updateCount();setInterval(updateCount,1000);
const rsvp=document.querySelector('#rsvp-dialog');document.querySelectorAll('[data-rsvp]').forEach(b=>b.addEventListener('click',()=>rsvp.showModal()));document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
const form=document.querySelector('#rsvp-form'),result=document.querySelector('#rsvp-result');form.elements.attendance.addEventListener('change',()=>{form.elements.guests.disabled=form.elements.attendance.value!=='Joyfully attending'});form.addEventListener('submit',e=>{e.preventDefault();const data=new FormData(form),name=String(data.get('name')).trim();if(!name){form.elements.name.setCustomValidity('Please enter your name.');form.elements.name.reportValidity();return}form.elements.name.setCustomValidity('');const attending=data.get('attendance')==='Joyfully attending';const message=`ప్రియమైన ఆర్య & అర్జున్,\n\n${name}: ${attending?'సంతోషంగా వస్తున్నాం':'రాలేకపోతున్నాం'}.${attending?'\nనాతో కలిపి మొత్తం అతిథులు: '+data.get('guests'):''}\nవివాహం: 14 ఫిబ్రవరి 2027${String(data.get('note')).trim()?'\n\n'+String(data.get('note')).trim():''}\n\nప్రేమతో,\n${name}`;document.querySelector('#reply-text').textContent=message;document.querySelector('#whatsapp').href='https://wa.me/?text='+encodeURIComponent(message);form.hidden=true;result.hidden=false});form.elements.name.addEventListener('input',()=>form.elements.name.setCustomValidity(''));document.querySelector('#edit-reply').addEventListener('click',()=>{form.hidden=false;result.hidden=true});
const photo=document.querySelector('#photo-dialog');document.querySelectorAll('[data-image]').forEach(b=>b.addEventListener('click',()=>{const img=document.querySelector('#full-photo');img.src=b.dataset.image;img.alt=b.querySelector('img').alt;document.querySelector('#full-caption').textContent=b.dataset.caption;photo.showModal()}));
function toast(text){const t=document.querySelector('.toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),4000)}
document.querySelector('#calendar').addEventListener('click',()=>{const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Royal Garden//Wedding Invitation//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT','UID:aarya-arjun-20270214@royalgarden.example','DTSTAMP:20260919T000000Z','DTSTART:20270214T050000Z','DTEND:20270214T083000Z','SUMMARY:Aarya & Arjun Wedding (Demo)','LOCATION:Sreerastu Kalyana Mandapam - fictional venue - Vizianagaram India','DESCRIPTION:Wedding ceremony at 10:30 AM IST. Wedding lunch at 12:30 PM IST. Fictional invitation demo.','END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='aarya-arjun-wedding.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('క్యాలెండర్ ఆహ్వానం సిద్ధమైంది.')});
